config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  resources :customers

  resources :services
  
  get 'pages/home'
  get 'pages/services'
  get 'pages/customers'
  resources :logs
  
  root to: 'pages#home'
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :vehicles
    has_many :logs

    validates :first_name, :last_name, :email, :phone_number, :secondary_phone_number, :address, :presence => true
    
    def display_name
        "#{first_name} #{last_name}"
    end
    
    def owned_vehicles
        vehicles.map(&:model).join(', ')
    end

    def owned_vehicles_make
        vehicles.map(&:make).join(', ')
    end

    def owned_vehicles_color
        vehicles.map(&:color).join(', ')
    end

    def owned_vehicles_plate
        vehicles.map(&:plates).join(', ')
    end

    def owned_vehicles_desc
        vehicles.map(&:description).join(', ')
    end

    def last_service_date
        return "No Record" if logs.count == 0
        logs.last.service_date.strftime("%m/%d/%Y")
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :email, :phone_number, :secondary_phone_number, :address)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <p>
    <strong>First name:</strong>
    <%= customer.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= customer.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= customer.email %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= customer.phone_number %>
  </p>

  <p>
    <strong>Secondary phone number:</strong>
    <%= customer.secondary_phone_number %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= customer.address %>
  </p>
  

</div>

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.number_field :phone_number %>
  </div>

  <div>
    <%= form.label :secondary_phone_number, style: "display: block" %>
    <%= form.number_field :secondary_phone_number %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Show this customer", @customer %> |
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <div class="container">
        <div class="row">
          <th class="col-1">First Name</th>
          <th class="col-1">Surname</th>
          <th class="col-1">Email</th>
          <th class="col-1">Phone Number</th>
          <th class="col-1">Secondary Phone Number</th>
          <th class="col-1">Vehicles</th>
          <th class="col-2">Address</th>
          <th class="col-2">Date of Last Service</th>
          <th colspan="1"></th>
        </div>
      </div>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <div class="container">
          <div class="row">
            <td class="col-1"><%= customer.first_name %></td>
            <td class="col-1"><%= customer.last_name %></td>
            <td class="col-1"><%= customer.email %></td>
            <td class="col-1"><%= customer.phone_number %></td>
            <td class="col-1"><%= customer.secondary_phone_number %></td>
            <td class="col-1"><%= customer.owned_vehicles %></td>
            <td class="col-2"><%= customer.address %></td>
            <td class="col-2"><%= customer.last_service_date%></td>
            <td class="col-1"><%= link_to "Show this customer", customer %></td>
        </div>
      </div>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to "New customer", new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @customer %>

<br>

<h3>Vehicles</h3>

<table>
  <thead>
    <tr>
      <div class="container">
        <div class="row">
          <th class="col-1">Make</th>
          <th class="col-1">Model</th>
          <th class="col-1">Color</th>
          <th class="col-1">Plate Number</th>
          <th class="col-1">Description</th>
          <th colspan="1"></th>
        </div>
      </div>
    </tr>
  </thead>
  <tbody>
    <% if @customer.vehicles.empty? %>
      <div class="container">
          <tr>
            <div class="row">
                <td class=""><button><%= link_to "New vehicle", new_vehicle_path %></button></td>
            </div>
          </tr>
      </div>
    <% else %>
      <div class="container">
        <% @customer.vehicles.each do |vehicle| %>
          <tr>
            <div class="row">
                <td class="col-1"><%= vehicle.make %></td>
                <td class="col-1"><%= vehicle.model %></td>
                <td class="col-1"><%= vehicle.color %></td>
                <td class="col-1"><%= vehicle.plates %></td>
                <td class="col-1"><%= vehicle.description %></td>
            </div>
          </tr>
        <% end %>
      </div>
    <% end %>
  </tbody>
</table>

<div>
  <%= link_to "Edit this customer", edit_customer_path(@customer) %> |
  <%= link_to "Back to customers", customers_path %>

  <%= button_to "Destroy this customer", @customer, method: :delete %>
</div>