config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  resources :customers

  resources :services
  
  get 'pages/home'
  get 'pages/services'
  get 'pages/customers'
  resources :logs
  
  root to: 'pages#home'
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
    belongs_to :customer,  optional: true
    has_many :logs

    mount_uploader :vehicle_source, ImageUploader

    validates :make, :model, :color, :customer_id, :plates, :description, :presence => true

    def display_model
        "#{model}"
    end

    def display_owner
        customer&.display_name
    end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: %i[ show edit update destroy ]

  # GET /vehicles or /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1 or /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles or /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to vehicle_url(@vehicle), notice: "Vehicle was successfully created." }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1 or /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to vehicle_url(@vehicle), notice: "Vehicle was successfully updated." }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1 or /vehicles/1.json
  def destroy
    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: "Vehicle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_params
      params.require(:vehicle).permit(:make, :vehicle_source, :model, :color, :customer_id, :plates, :description)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle) do |form| %>
  <% if vehicle.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
        <% vehicle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :make, style: "display: block" %>
    <%= form.text_field :make %>
  </div>

  <div>
    <%= form.label :model, style: "display: block" %>
    <%= form.text_field :model %>
  </div>

  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.text_area :color %>
  </div>

  <div>
    <%= form.label :owner, style: "display: block" %>
    <%= collection_select(:vehicle, :customer_id, Customer.all, :id, :display_name, prompt: true) %>
  </div>

  <div>
    <%= form.label :plates, style: "display: block" %>
    <%= form.text_field :plates %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.file_field :vehicle_source %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/_vehicle.html.erb
<div id="<%= dom_id vehicle %>">
  <p>
    <strong>Make:</strong>
    <%= vehicle.make %>
  </p>

  <p>
    <strong>Model:</strong>
    <%= vehicle.model %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= vehicle.color %>
  </p>

  <p>
    <strong>Owner:</strong>
    <%= vehicle.display_owner %>
  </p>

  <p>
    <strong>Plates:</strong>
    <%= vehicle.plates %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= vehicle.description %>
  </p>

  <p>
    <strong>Image:</strong>
  </p>
    <%= image_tag @vehicle.vehicle_source.url, class: "vehicle-show" %>

</div>

app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render "form", vehicle: @vehicle %>

<br>

<div>
  <%= link_to "Show this vehicle", @vehicle %> |
  <%= link_to "Back to vehicles", vehicles_path %>
</div>

app/views/vehicles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Vehicles</h1>
<table>
  <thead>
    <tr>
      <div class="container">
        <div class="row">
          <th class="col-1">Make</th>
          <th class="col-1">Model</th>
          <th class="col-1">Color</th>
          <th class="col-1">Customer ID</th>
          <th class="col-1">Plate Number</th>
          <th class="col-2">Description</th>
          <th colspan="1"></th>
        </div>
      </div>
    </tr>
  </thead>
  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <div class="container">
          <div class="row">
            <td class="col-1"><%= vehicle.make %></td>
            <td class="col-1"><%= vehicle.model %></td>
            <td class="col-1"><%= vehicle.color %></td>
            <td class="col-1"><%= vehicle.display_owner %></td>
            <td class="col-1"><%= vehicle.plates %></td>
            <td class="col-2"><%= vehicle.description %></td>
            <td class="col-1"><%= link_to "Show this vehicle", vehicle %></td>
        </div>
      </div>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to "New vehicle", new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New vehicle</h1>

<%= render "form", vehicle: @vehicle %>

<br>

<div>
  <%= link_to "Back to vehicles", vehicles_path %>
</div>

app/views/vehicles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vehicle %>

<div>
  <%= link_to "Edit this vehicle", edit_vehicle_path(@vehicle) %> |
  <%= link_to "Back to vehicles", vehicles_path %>

  <%= button_to "Destroy this vehicle", @vehicle, method: :delete %>
</div>