config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  resources :customers

  resources :services
  
  get 'pages/home'
  get 'pages/services'
  get 'pages/customers'
  resources :logs
  
  root to: 'pages#home'
end

app/models/log.rb
class Log < ApplicationRecord
    # belongs_to :service, optional: true
    # TAGS = %i[in out in-and-out]
    paginates_per 5
    has_many :availed_services
    has_many :services, through: :availed_services

    belongs_to :customer, optional: true
    belongs_to :vehicle, optional: true

    STATUS = %i[paid unpaid partially_paid]

    enum status: [:unpaid, :paid, :void]

    validates :customer_id, :vehicle_id, :services, :presence => true

    def display_services
      services.map(&:title).join(', ')
    end

    def display_customer
      customer&.display_name
    end

    def display_vehicle
      vehicle&.model
    end

    def display_price
      services.sum(:rate)
    end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: %i[ show edit update destroy ]

  # GET /logs or /logs.json
  def index
    @logs = Log
      .all
      .page(params[:page] || 1)
  end

  # GET /logs/1 or /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs or /logs.json
  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to log_url(@log), notice: "Log was successfully created." }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1 or /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to log_url(@log), notice: "Log was successfully updated." }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1 or /logs/1.json
  def destroy
    @log.destroy

    respond_to do |format|
      format.html { redirect_to logs_url, notice: "Log was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def log_params
      params.require(:log).permit(:title, :display_name, :display_model, :vehicle_id, :service_date,:display_services, :customer_id, :body, :model, :service_id, :status, service_ids: [], tags: [])
    end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_with(model: log) do |form| %>
  <% if log.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
        <% log.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :customer, style: "display: block" %>
    <%= collection_select(:log, :customer_id, Customer.all, :id, :display_name, prompt: true) %>
  </div>

  <div>
    <%= form.label :car, style: "display: block" %>
    <%= collection_select(:log, :vehicle_id, Vehicle.all, :id, :display_model, prompt: true)%>
  </div>

  <div class="field">
      <%= form.label :services, style: "display: block" %>
      <%= hidden_field_tag "log[service_ids][]", nil%>
    <% Service.all.each do |service|%>
      <%= check_box_tag "log[service_ids][]", service.id, @log.services.include?(service), id: dom_id(service)%>
      <%= label_tag dom_id(service), service.title%><br>
    <% end %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_select :service_date %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    
    <%= form.select :status, Log.statuses.keys.map %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/logs/_log.html.erb
<div id="<%= dom_id log %>">
  <p>
    <strong>Customer:</strong>
    <%= log.display_customer %>
  </p>

  <p>
    <strong>Car Model:</strong>
    <%= log.display_vehicle %>
  </p>
  <p>
    <strong>Service Availed:</strong>
    <%= log.display_services %>
  </p>
  <p>
    <strong>Status:</strong>
    <%= log.status %>
  </p>

  <p>
    <strong>Total Price:</strong>
    <%= log.display_price %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= log.service_date&.strftime("%m-%d-%Y") %>
  </p>

</div>

app/views/logs/edit.html.erb
<h1>Editing log</h1>

<%= render "form", log: @log %>

<br>

<div>
  <%= link_to "Show this log", @log %> |
  <%= link_to "Back to logs", logs_path %>
</div>

app/views/logs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Logs</h1>

<%= Log.count %>

<%= paginate @logs %>

<table>
  <thead>
    <tr>
      <div class="container">
        <div class="row">
          <th class="col-2">Name</th>
          <th class="col-2">Car Model</th>
          <th class="col-3">Service Availed</th>
          <th class="col-1">Status</th>
          <th class="col-2">Date</th>
          <th class="col-1">Total</th>
          <th colspan="1"></th>
        </div>
      </div>
    </tr>
  </thead>
  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <div class="container">
          <div class="row">
            <td class="col-2"><%= log.display_customer %></td>
            <td class="col-2"><%= log.display_vehicle %></td>
            <td class="col-3"><%= log.display_services %></td>
            <td class="col-1"><%= log.status %></td>
            <td class="col-2"><%= log.service_date&.strftime("%m-%d-%Y") %></td>
            <td class="col-1"><%= log.display_price %></td>
            <td class="col-1"><%= link_to "Show this log", log %></td>
        </div>
      </div>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @logs %>


<%= link_to "New log", new_log_path %>

app/views/logs/new.html.erb
<h1>New log</h1>

<%= render "form", log: @log %>

<br>

<div>
  <%= link_to "Back to logs", logs_path %>
</div>

app/views/logs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @log %>

<div>
  <%= link_to "Edit this log", edit_log_path(@log) %> |
  <%= link_to "Back to logs", logs_path %>

  <%= button_to "Destroy this log", @log, method: :delete %>
</div>